### ISSUE TITLE
The prompt rendering of the final images are always black.

### ISSUE THREAD

**Issue by zov-coder** [SeargeDP/SeargeSDXL#37]
Hi Searge.
Having issue at the end of the prompt rendering and the final images are always black.

**So this is the entire log message :** 

E:\...\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --normalvram --fp16-vae
** ComfyUI start up time: 2023-08-12 19:40:13.776386
Prestartup times for custom nodes:
   0.0 seconds: E:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 98211 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro M4000 : native
Using xformers cross attention
### ComfyUI Revision: 1274 [2bc12d3d]

Import times for custom nodes:
   0.0 seconds: E:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.5 seconds: E:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Failed to validate prompt for output 364:
* ImageUpscaleWithModel 66:
  - Required input is missing: image
* ImageUpscaleWithModel 67:
  - Required input is missing: image
Output will be ignored
Failed to validate prompt for output 243:
Output will be ignored
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
....
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 2048 and using 10 heads.
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Setting up MemoryEfficientCrossAttention. Query dim is 768, context_dim is None and using 12 heads.
.....
Setting up MemoryEfficientCrossAttention. Query dim is 768, context_dim is 1280 and using 12 heads.
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
100%|#####################################################| 24/24 [04:36<00:00, 11.52s/it]
100%|#####################################################| 6/6 [01:08<00:00, 11.40s/it]
E:\...\ComfyUI_windows_portable\ComfyUI\nodes.py:1269: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
E:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\searge_sdxl_sampler_node.py:359: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
E:\...\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Prompt executed in 423.31 seconds

End of log.

I'm using in ops mod : txt2img, prompt style : simple with default settings and all models are loaded correctly.
Thanks in advance for your response.

**Comment by SeargeDP** [comment]
Are you using the latest .json file of the workflow (v3.4)? The warning for `E:...\ComfyUI_windows_portable\ComfyUI\nodes.py:1269` is from a node that I'm not using anymore in more recent versions of the workflow (The Comfy SaveImage node, I replaced it with a custom save image node type).

**Comment by TomTomGit86** [comment]
im having this same issue too now i started with fresh comfyui install and the this customnodes only and getting black output images

**Comment by TomTomGit86** [comment]
download [Fixed SDXL 0.9 vae](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors) and copy it into ComfyUI/models/vae

i think i just fixed the black output images make sure you dowmload and use this VAE

**Comment by zov-coder** [comment]
Yes @SeargeDP  I'm using the latest .json file of the workflow i.e **(v3.4)** as specified during the installation instructions. Also, I have already installed the fine-tuned VAE decoder **(Fixed SDXL 0.9 vae)** into ComfyUI/models/vae folder as mentioned by @TomTomGit86. Unfortunately I still have the same issue.

**Comment by TomTomGit86** [comment]
https://civitai.com/models/111463

Try the one here 
https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors

**Comment by TomTomGit86** [comment]
I've also installed comfyui manager to check for and Install any missing nodes and do updates a lil more user friendly

**Comment by SeargeDP** [comment]
Do you have other node extensions installed? In that case please try with just my extension and tell me if that makes a difference. Want to figure out if there is some incompatibility with other extensions.

**Comment by TomTomGit86** [comment]
I did uninstall other extensions to eliminate this but I have since re-installed WAS Node Suite - ComfyUI and it still worked with this installed I think ive gone back to auto1111 as I want to do more loopbackwaves looks like its gonna take a long time with the higher res and improper use denoiesing pic rather than working with laten data

**Comment by zov-coder** [comment]
> Do you have other node extensions installed? In that case please try with just my extension and tell me if that makes a difference. Want to figure out if there is some incompatibility with other extensions.

Yes I uninstalled other extensions and it worked fine for me. Thanks Searge for your kind help.

**Comment by SeargeDP** [comment]
I'll close this now, it seems that either uninstalling conflicting node extensions or using a different VAE can solve this issue.
